### ISSUE TITLE
Olga 0 pages very slow

### ISSUE THREAD

**Issue by JulienOlga** [aleray/aa.olga#12]
It goes quite slow in general for Olga0 pages to be uploaded. So the new server and the freezing doesn't bring a solution to the problem we know about most of the pages of "more than one tie"or Lisa Nelson's interview on "what's the score?" :
It takes so long to get the audio that the visitor should think its either not working or that he's proposed a mute slideshow (especially as this cinematic pages do not provide any icons showing that the uploading is in progress)
What could be done about this?

**Comment by aleray** [comment]
Should be much better now. The embeds are backed in the HTMl and not loaded afterward.

**Comment by JulienOlga** [comment]
It is indeed much better, yet still sufficiently long to puzzle and discourage visitors if they don't know it's loading.
1- Could it still be improved? 
    And
2- Could a message or an icon appear to let people know it's loading? (like the pop-up box saying one should use Firefox)
